export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Skills } from './Skills';
export { default as Academics } from './Academics';
export { default as Projects } from './Projects';
export { default as Profiles } from './Profiles';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as DarkModeToggle } from './DarkModeToggle';
